version: '3.7'
services:
  app:
    container_name: myapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    tty: true
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: local_go
      MYSQL_USER: gopher
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local
